# Generated by Django 5.2.1 on 2025-06-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(default='', help_text='Nombre del autor o persona que registró el producto', max_length=100),
        ),
    ]
