# Generated by Django 5.2.1 on 2025-06-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cartitem_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tbk_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token Webpay'),
        ),
    ]
